### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=JetBrains Rider

### Authentication Request
POST https://439d9c21-93d9-4665-8d82-6353c8a13cce.mock.pstmn.io/api/v1/auth/key
Content-Type: application/json

{
  "type": "REST",
  "key": "jrYRtDchsg1xudxH"

}
###Get Wall Brightness with Cookie
GET https://439d9c21-93d9-4665-8d82-6353c8a13cce.mock.pstmn.io/api/v1/wall/brightness
Cookie: sid=8NCshAkEZqdThUJsixQn41bJvlXjkEtjpnEeAz98